version: '3.1'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/var/lib/mongo

volumes:
  mongo-data: